################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
networks:
  frontend:
    internal: false
services:
  spring-petclinic:
    deploy:
      placement:
        constraints:
        - node.role == worker
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    image: academiaonline/spring-petclinic:1.1
    networks:
    - frontend
    ports:
      - 30000:8080
version: '3.8'
