################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template: 
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers: 
      -
        image: academiaonline/spring-petclinic:latest
        imagePullPolicy: Always
        name: spring-petclinic
        ports:
        -
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 500m
            memory: 1G          
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spring-petclinic
spec:
  ingress:
  -
    ports:
    -
      port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: spring-petclinic
---
apiVersion: v1
kind: Service
metadata: 
  name: spring-petclinic
spec:
  ports:
  -
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-petclinic
  type: NodePort
---  
