#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
# docker run --detach --entrypoint java --name spring-petclinic --publish 8080 --user nobody:nobody --workdir /app/ docker.io/academiaonline/spring-petclinic:latest -jar java.jar
---
apiVersion: v1
kind: Pod
metadata:
  name: spring-petclinic-po
  labels:
    app: spring-petclinic-po
spec:
  containers:
    - name: spring-petclinic-container
      args:
        - -jar
        - java.jar
      command:
        - java
      image: docker.io/academiaonline/spring-petclinic:latest
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534
      workingDir: /app/
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-po
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: spring-petclinic-po
  type: NodePort
---
