################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
# docker run --detach --entrypoint java --name spring-petclinic --publish 8080 --user nobody:nobody --workdir /app/ docker.io/academiaonline/spring-petclinic:latest -jar java.jar
services:
  spring-petclinic:
    command:
      - -jar
      - java.jar
    entrypoint: java
    image: docker.io/academiaonline/spring-petclinic:latest
    ports:
      - 8080
    user: nobody:nobody
    working_dir: /app/
version: "3.9" 
