apiVersion: v1
kind: Pod
metadata:
  name: spring-petclinic-po
  labels:
    app: spring-petclinic
spec:
  containers:
    - name: spring-petclinic-container
      image: secobau/spring-petclinic:1.2
      ports:
        - containerPort: 8080
